server:
  port: 8087
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://rm-wz9nd973maez52c107o.mysql.rds.aliyuncs.com:3306/huangniuniu
    username: jc
    password: jc123456AA

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 10秒不发送就过期
mybatis:
  type-aliases-package: com.huangniuniu.order.pojo
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名

huangniuniu:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: Huangniuniu_TOKEN  #cookie名称
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 # 熔断器的超时时长：5000ms
ribbon:
  ConnectionTimeout: 3000  # ribbon的连接时长：1000ms
  ReadTimeout: 35000  # ribbon的读取时长：3500ms
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 0  # 切换服务重试次数
feign:
  httpclient:
    enabled: true
