server:
  port: 8083
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/huangniuniu
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 10秒不发送就过期