server:
  port: 8081
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB  #上传文件的大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
#设置fastdfs配置
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 47.102.97.195:22122